### ISSUE TITLE
Source build: where is the executable?

### ISSUE THREAD

**Issue by Ethanol6** [tryton-vanmeer/DungeonJournal#18]
Hello,

I compiled from source but I do not know where the executable file is. I can find the .desktop file in the build directory but the parameter `Exec=dungeonjournal` does not actually execute anything. Typing `dungeonjournal` right in the terminal reports `command not found` so there's nothing in the usual /bin paths.

**Comment by trytonlux** [comment]
After building, the binary is in build/src. Running it directly will fail since you need the gschema installed.

If you're just compiling and testing this out, GNOME Builder would be the simplest way to go.
